platform :ios, '7.0'
inhibit_all_warnings!

target 'JasonBlog' do
    
pod "AFNetworking", '~> 2.5.3'
pod 'SDWebImage', '~> 3.7.2'
pod 'SBJson', '~> 4.0.1'
pod 'Cordova', '~> 3.8.0'
pod 'CordovaPlugin-device', '~> 0.2.11'
pod 'MJRefresh', '~> 1.4.6'
pod 'Masonry', '~> 0.6.1'
pod 'CordovaPlugin-battery-status', '~> 0.2.10'
pod 'JBASIHTTPRequest', '~> 2.1'
pod 'ReactiveCocoa'
pod 'LazyScroll'
pod 'DTRichTextEditor', '~> 1.6.12'
pod 'WebViewJavascriptBridge', '~> 5.0'

end
